"""Core abstractions for GeoNeuronX.

This module is deliberately small and explicit.  It does not claim to be a
biophysical neuron simulator.  It exposes the mathematical seam we want to
attack:

    path length -> transfer coefficient / delay -> temporal feature bank
                -> learned projection -> soma -> adaptive AIS -> axon event

The first experiments use theorem-friendly linear source models so failures are
interpretable.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import numpy as np
from scipy.optimize import linear_sum_assignment

Array = np.ndarray


def ar1_source(a: float, n: int, rng: np.random.Generator) -> Array:
    """Generate a standardized AR(1) source with coefficient ``a``."""
    e = rng.normal(size=n)
    x = np.zeros(n, dtype=float)
    for t in range(1, n):
        x[t] = a * x[t - 1] + e[t]
    x -= x.mean()
    std = x.std()
    if std > 0:
        x /= std
    return x


def make_temporal_sources(
    n: int,
    rng: np.random.Generator,
    coefficients: Iterable[float] = (0.95, 0.45, -0.60),
) -> Array:
    """Return independent sources with deliberately different lag-1 memories.

    Columns are sources, shape ``(time, source)``.  Equal marginal variance is
    intentional: zero-lag variance should not be the whole answer.
    """
    return np.column_stack([ar1_source(a, n, rng) for a in coefficients])


def path_transfer_matrix(
    lengths: Array,
    carrier_frequencies: Array | tuple[float, ...] = (5.0, 11.0, 17.0),
    velocity: float = 25.0,
    attenuation: float = 0.15,
) -> Array:
    r"""Build a simple real transfer matrix generated by path length.

    For branch ``j`` and source/carrier ``i`` we use the real part of a delayed,
    attenuated phasor

        H_ji = exp(-attenuation * L_j) * cos(2*pi*f_i*L_j/velocity).

    This is not a cable-equation neuron model.  It is the smallest abstraction
    that makes the proposition testable: changing path length changes the
    coefficients seen at different temporal frequencies.
    """
    lengths = np.asarray(lengths, dtype=float)
    freqs = np.asarray(carrier_frequencies, dtype=float)
    tau = lengths / velocity
    return np.exp(-attenuation * lengths[:, None]) * np.cos(
        2.0 * np.pi * tau[:, None] * freqs[None, :]
    )


def effective_rank(matrix: Array, tol: float = 1e-12) -> int:
    s = np.linalg.svd(matrix, compute_uv=False)
    if len(s) == 0:
        return 0
    return int(np.sum(s > tol * s[0]))


def condition_number(matrix: Array, floor: float = 1e-12) -> float:
    s = np.linalg.svd(matrix, compute_uv=False)
    if len(s) == 0:
        return float("inf")
    return float(s[0] / max(float(s[-1]), floor))


def observe_through_morphology(
    sources: Array,
    lengths: Array,
    rng: np.random.Generator,
    noise_std: float = 0.03,
) -> tuple[Array, Array]:
    """Map hidden source amplitudes to branch-local observations."""
    A = path_transfer_matrix(lengths)
    x = sources @ A.T
    if noise_std > 0:
        x = x + noise_std * rng.normal(size=x.shape)
    return x, A


def pca_scores(x: Array, n_components: int) -> Array:
    x0 = x - x.mean(axis=0, keepdims=True)
    _, _, vt = np.linalg.svd(x0, full_matrices=False)
    k = min(n_components, vt.shape[0])
    return x0 @ vt[:k].T


def whiten(x: Array, n_components: int, eps: float = 1e-10) -> tuple[Array, Array]:
    """Whiten observations and return ``(x_white, whitening_matrix)``."""
    x0 = x - x.mean(axis=0, keepdims=True)
    cov = (x0.T @ x0) / len(x0)
    vals, vecs = np.linalg.eigh(cov)
    order = np.argsort(vals)[::-1]
    vals = vals[order]
    vecs = vecs[:, order]
    if len(vals) == 0 or vals[0] <= 0:
        return np.zeros((len(x), 0)), np.zeros((x.shape[1], 0))
    keep = vals > eps * vals[0]
    vals = vals[keep]
    vecs = vecs[:, keep]
    k = min(n_components, len(vals))
    vals = vals[:k]
    vecs = vecs[:, :k]
    W0 = vecs @ np.diag(1.0 / np.sqrt(vals))
    return x0 @ W0, W0


def amuse(x: Array, n_components: int, lag: int = 1) -> Array:
    """AMUSE: whiten, then diagonalize one symmetrized lag covariance."""
    if lag < 1:
        raise ValueError("lag must be >= 1")
    xw, _ = whiten(x, n_components=n_components)
    if xw.shape[1] == 0 or len(xw) <= lag:
        return np.zeros((len(x), 0))
    c_tau = (xw[:-lag].T @ xw[lag:]) / (len(xw) - lag)
    c_tau = 0.5 * (c_tau + c_tau.T)
    vals, vecs = np.linalg.eigh(c_tau)
    # Ordering does not matter for BSS, but deterministic sorting makes receipts stable.
    order = np.argsort(np.abs(vals))[::-1]
    return xw @ vecs[:, order]


def recovery_score(estimated: Array, truth: Array) -> tuple[float, Array]:
    """Permutation/sign-invariant mean absolute source correlation."""
    if estimated.size == 0:
        return 0.0, np.zeros((0, truth.shape[1]))
    joined = np.corrcoef(estimated.T, truth.T)
    p = estimated.shape[1]
    corr = np.abs(joined[:p, p:])
    rows, cols = linear_sum_assignment(-corr)
    return float(np.mean(corr[rows, cols])), corr


def oja_first_component(
    x: Array,
    lr: float = 2e-4,
    seed: int = 0,
    renorm_every: int = 500,
) -> tuple[Array, Array]:
    """Online Oja rule for one component.

    ``dw = lr * y * (x - y*w)``.  The subtraction is the self-limiting term;
    Oja normalizes the learned weight dynamics, not the incoming signal itself.
    """
    rng = np.random.default_rng(seed)
    x0 = x - x.mean(axis=0, keepdims=True)
    w = rng.normal(size=x.shape[1])
    w /= np.linalg.norm(w) + 1e-12
    y = np.zeros(len(x0))
    for t, xt in enumerate(x0):
        yt = float(np.dot(w, xt))
        y[t] = yt
        w += lr * yt * (xt - yt * w)
        if renorm_every and (t + 1) % renorm_every == 0:
            w /= np.linalg.norm(w) + 1e-12
    w /= np.linalg.norm(w) + 1e-12
    return y, w


def best_single_source_correlation(signal: Array, truth: Array) -> float:
    vals = [abs(np.corrcoef(signal, truth[:, i])[0, 1]) for i in range(truth.shape[1])]
    return float(np.max(vals))


@dataclass
class AdaptiveAIS:
    """Minimal homeostatic axon-initial-segment abstraction.

    ``threshold`` is an effective spike-initiation threshold, not a literal AIS
    position in micrometers.  Higher sustained firing pushes the threshold up;
    low firing pulls it down.  This mirrors the *functional direction* of AIS
    homeostatic plasticity while keeping the implementation honest and small.
    """

    target_rate: float = 0.10
    threshold: float = 1.18
    learning_rate: float = 0.01
    rate_alpha: float = 0.01
    min_threshold: float = -2.0
    max_threshold: float = 6.0

    def __post_init__(self) -> None:
        self.rate_trace = float(self.target_rate)

    def step(self, soma_voltage: float) -> int:
        spike = int(soma_voltage > self.threshold)
        self.rate_trace = (
            (1.0 - self.rate_alpha) * self.rate_trace
            + self.rate_alpha * spike
        )
        self.threshold += self.learning_rate * (self.rate_trace - self.target_rate)
        self.threshold = float(np.clip(self.threshold, self.min_threshold, self.max_threshold))
        return spike


def soma_from_branches(branch_activity: Array) -> Array:
    """A bounded nonlinear soma readout used by the AIS control experiment."""
    if branch_activity.ndim != 2:
        raise ValueError("branch_activity must have shape (time, branch)")
    return np.tanh(branch_activity).sum(axis=1) / np.sqrt(branch_activity.shape[1])
